### ISSUE TITLE
cannot detect gnu make

### ISSUE THREAD

**Issue by iliazark** [PeakSat/minimal-dev-setup#10]
samv71-dfp/4.9.117: CMakeToolchain generated: conan_toolchain.cmake
samv71-dfp/4.9.117: CMakeToolchain generated: C:\Users\iliaz\.conan2\p\b\samv7c8d03322f3429\b\build\Release\generators\CMakePresets.json
samv71-dfp/4.9.117: CMakeToolchain generated: C:\Users\iliaz\.conan2\p\b\samv7c8d03322f3429\b\CMakeUserPresets.json
samv71-dfp/4.9.117: Generating aggregated env files
samv71-dfp/4.9.117: Generated aggregated env files: ['conanbuild.bat', 'conanrun.sh']
samv71-dfp/4.9.117: Calling build()
samv71-dfp/4.9.117: Running CMake.configure()
samv71-dfp/4.9.117: RUN: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/iliaz/.conan2/p/b/samv7c8d03322f3429/p" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "C:/Users/iliaz/.conan2/p/b/samv7c8d03322f3429/b"
-- Using Conan toolchain: C:/Users/iliaz/.conan2/p/b/samv7c8d03322f3429/b/build/Release/generators/conan_toolchain.cmake
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

samv71-dfp/4.9.117: ERROR:
Package 'e484a1bb7a78d7d564dde45dc3f4dab5b65736f1' build failed
samv71-dfp/4.9.117: WARN: Build folder C:\Users\iliaz\.conan2\p\b\samv7c8d03322f3429\b\build\Release
ERROR: samv71-dfp/4.9.117: Error in build() method, line 72
        cmake.configure()
        ConanException: Error 1 while executing

**Comment by lightspot21** [comment]
After live troubleshooting, it seems that CMake 3.30.0 assumes the make executable to be named "mingw32-make" on Windows. On @iliazark 's pc we had GnuWin32 make installed, to prevent the use of an entire package manager just for

Possible solutions:
- Use Ninja instead of Make. Simpler, should need no hacks, as Ninja is designed to work out of the box on Windows too. Specifying Ninja on the profile (`tools.cmake.cmaketoolchain:generator=Ninja`) should also make it transparent to the user.
- Somehow install from MinGW only the make executable 
- Install GnuWin32 make and rename that to mingw32-make (hacky)

**Comment by lightspot21** [comment]
Done, latest master incorporates ninja
